plugins { id 'java'; id 'maven-publish'; id 'net.minecraftforge.gradle' version '[7.0.29,8.0)' }
version=mod_version
group=mod_group_id
base { archivesName=mod_id }
java.toolchain.languageVersion=JavaLanguageVersion.of(21)
minecraft {
 mappings channel:'official',version:minecraft_version
 runs { configureEach { workingDirectory project.file('run'); systemProperty 'forge.logging.console.level','debug' } client { systemProperty 'forge.enabledGameTestNamespaces',project.mod_id } server { systemProperty 'forge.enabledGameTestNamespaces',project.mod_id; args '--nogui' } }
}
repositories { minecraft.mavenizer(it); maven fg.forgeMaven; maven fg.minecraftLibsMaven; mavenCentral() }
dependencies { implementation minecraft.dependency("net.minecraftforge:forge:"+minecraft_version+"-"+forge_version) }
tasks.withType(ProcessResources).configureEach { def replaceProperties=[minecraft_version:minecraft_version,minecraft_version_range:minecraft_version_range,forge_version:forge_version,forge_version_range:forge_version_range,mod_id:mod_id,mod_name:mod_name,mod_license:mod_license,mod_version:mod_version,mod_authors:mod_authors,mod_description:mod_description]; inputs.properties replaceProperties; filesMatching(['META-INF/mods.toml']) { expand replaceProperties } }
tasks.withType(JavaCompile).configureEach { options.encoding='UTF-8' }
